### ISSUE TITLE
Send model and data in emitters as attributes of the model

### ISSUE THREAD

**Issue by juanfadev** [Arquisoft/dashboard_i3b#2]
proposals variable is updated from database whenever an update comes
it then sends data as raw text toString() to the browser using a foreach of proposals

```
@RequestMapping(path = "/", method = RequestMethod.POST)
    @KafkaListener(topics = "updates")
    public String showMessage(String data) {
        proposals = service.getAllProposal();
        synchronized (this.sseEmitters) {
            for (SseEmitter sseEmitter : this.sseEmitters) {

                proposals.parallelStream().forEach(c -> {
                    try {
                        sseEmitter.send(c.toString());
                    } catch (Exception e) {
                        logger.error("Se ha cerrado el navegador");
                    }
                });

            }
        }
        //creo que aqui se puede mandar un modelo y data como un atributo del modelo igual que la anterior vez
        return data;
    }
```

We sould need to send model to the view and send the emitter data as an attribute of the model, not the data itself as raw text

**Comment by juanfadev** [comment]
@guille I've just changed this. If you check index.html you can see how it gets events from different urls, and parse them as an element in the dom using EventSource in <script> tags. 

You may adapt the information given as you wish, to a new style you give to index. If you need more information or different information to be sent to the view and you dont know how. Please mention @juanfpo96

**Comment by guille** [comment]
@juanfpo96 I've created a new branch where I'm testing an alternate approach. While this allows for easy data manipulation and presentation (for example, the screenshot attached's result was really simple to achieve) constantly updating the whole page at that rate doesn't allow for any user action.

If you can get something similar with the EventSources I can migrate the other back-end stuff I implemented, such as upvoting proposals, the Regex matcher that identifies events from Kafka logs, etc. Otherwise I can try to slow down the rate at which the page updates itself.

I've pushed my code to TestAJAXImplementation branch if you want to take a look (the changes to Proposal, DBService and ProposalRepository need to be migrated to master sooner or later anyway). Let me know what you think.

![2017-03-30-18 33 06](https://cloud.githubusercontent.com/assets/1296511/24515392/c2ee31ca-1577-11e7-89ad-31ed3f5371d8.png)

**Comment by juanfadev** [comment]
@guille we can leave the SseEmitters for the logs (that are Strings of data to show) and we can do the AJAX way the model update. 

If you agree with this. Then please close the issue.
